version: '2'
services:
  client:
    # Step 5.1 - Point build step to the client directory
    image: react-app-production
    restart: unless-stopped
    ports:
      # Step 5.2 - Add the port that the client application runs on - (port:port).
      - '3000:3000'  
  server:
    # Step 5.3 - Point build step to the server directory
    image: server
    restart: unless-stopped
    env_file: ./config/${ENV}.env
    ports:
      # Step 5.4 - Add the port that the server application runs on - (port:port).
      - '3001:3001'    